### PR TITLE
Use WordPress Playground

### LINKED ISSUE #71: Blueprint support
If a plugin requires some sort of setup before running tests. For example Yoast, WooCommerce, or Site Kit.

This could include things like setting some options, etc.

Right now this is probably best achieved by adding another plugin that does all of this. A blueprint would just make it easier.

### LINKED ISSUE #81: Consider using WordPress Playground for tests
For a more lightweight setup, it might be possible to use wp-now instead of wp-env for the WordPress environment. Right now that doesn't seem realistic though due to lack of feature parity. And more complex setups (e.g. with object cache) won't be possible either.

### PR DESCRIPTION
**Pull request by swissspidy**
Fixes #71
Fixes #81

This replaces wp-env with WordPress Playground, using a blueprint to configure the test environment, making it easy to replicate the same environment locally as well.

Plus, the user can provide **their own blueprint**, which will be merged with the base one.

In a next step, I am considering using blueprints for the test scenarios themselves as well. This way, we can do more than just simply visiting URLs & measuring Server-Timing. For example, we could declaratively tell the action to fill out forms so things like INP can be measured. See https://github.com/swissspidy/wp-performance-action/issues/174

### Workflow

```yaml
    - name: Run performance tests
      uses: ./
      with:
        urls: |
          /
          /sample-page/
        # Simply mounts the plugin to `wp-content/plugins/dummy-plugin`
        plugins: |
          ./path/to/my/dummy-plugin
        blueprint: './path/to/my/blueprint.json'
        iterations: 5
        repetitions: 1
        wp-version: 'trunk'
        php-version: '7.4'
```

### User-provided blueprint

```json
{
  "$schema": "https://playground.wordpress.net/blueprint-schema.json",
  "plugins": [
    "performant-translations",
    "akismet"
  ],
  "steps": [
    {
      "step": "defineWpConfigConsts",
      "consts": {
        "WP_DEBUG": true
      }
    },
    {
      "step": "activatePlugin",
      "pluginName": "Dummy Plugin",
      "pluginPath": "/wordpress/wp-content/plugins/dummy-plugin"
    }
  ]
}
```

----

## Some observations

- TTFB is 5x higher, but starting the server is quicker.
- Playground is not always very stable. For example, I tried installing `wordpress-seo` in a blueprint and it crashed every time when trying to start the server.
	- Update: caused by the SQLite integration

To-do:

- [ ] Update documentation
- [ ] Improve how blueprints are merged, see https://github.com/WordPress/wordpress-playground/discussions/1631#discussioncomment-10663421
- [x] Add example with comparing with previous results

### CODE REVIEW

**Comment by swissspidy** [comment]
**Performance Test Results**

Performance test results for [6b350fe](https://github.com/swissspidy/wp-performance-action/commit/6b350fea407471d40576781d10d1444a80a4f4f9) are in 🛎️!

**Tests**

| Run | largestContentfulPaint | timeToFirstByte | lcpMinusTtfb |
| --- | ---------------------- | --------------- | ------------ |
|   0 |              446.80 ms |       322.85 ms |    122.15 ms |
|   1 |              444.80 ms |       323.75 ms |    119.70 ms |

**Comment by swissspidy** [comment]
In https://github.com/swissspidy/compare-wp-performance/pull/17 the results seemed less stable than when using wp-env. Not sure I can say the same here 🤔  Worth keeping an eye on.

**Comment by adamziel** [comment]
This is lovely! Are there any blockers for this work on the Playground side that we could help with?

> Playground is not always very stable. For example, I tried installing wordpress-seo in a blueprint and it crashed every time when trying to start the server.

@bgrgicak's is workon on [reporting installation errors](https://github.com/bgrgicak/playground-tester) for each plugin in the WordPress plugins repository to help fix them and potentially communicate known issues within Playground. That plugin came up in the work. The error in the web version of Playground is `CREATE UNIQUE INDEX `wp_yoast_migrations_version` ON `wp_yoast_migrations`(`version`)`, so the SQLite integration is at fault. I hope https://github.com/WordPress/sqlite-database-integration/pull/157 will either solve or make it easy to solve many SQLite issues.

**Comment by adamziel** [comment]
> For example, over at https://github.com/swissspidy/compare-wp-performance/pull/17, some of the gathered metrics didn't seem very stable with Playground.

I hear you! I'd like to investigate but I'm not sure how to connect the tabular data to the conclusion the metrics aren't stable. Would you help me connect these dots?

**Comment by swissspidy** [comment]
> > For example, over at [swissspidy/compare-wp-performance#17](https://github.com/swissspidy/compare-wp-performance/pull/17), some of the gathered metrics didn't seem very stable with Playground.
> 
> I hear you! I'd like to investigate but I'm not sure how to connect the tabular data to the conclusion the metrics aren't stable. Would you help me connect these dots?

Sure, so what that script in that repo does is measure things like the the TTFB difference between two WordPress versions. It does so over 100 iterations and then returns metrics such as the p50 value and standard deviation.

In https://github.com/swissspidy/compare-wp-performance/pull/17 I did this using both wp-env and Playground.

I just [re-ran](https://github.com/swissspidy/compare-wp-performance/pull/17#issuecomment-2370814802) those tests now, comparing WordPress nightly/trunk vs itself.

See [wp-env](https://github.com/swissspidy/compare-wp-performance/actions/runs/11011141358) result and [Playground](https://github.com/swissspidy/compare-wp-performance/actions/runs/11011146223) result.

I do have to say I like the results better now, but for values such as `wp-total`, wp-env sees barely a difference (p50 is 0.57 ms), whereas for Playground it is a bit higher (p50 is 3.50 ms).

**Comment by swissspidy** [comment]
The merging as per https://github.com/WordPress/wordpress-playground/discussions/1631 doesn't seem to work.

I'll probably keep the current approach until I can sort this out.

**Pull request merged**
